services:
  dev:
    build: .
    container_name: development
    volumes:
      - ./:/workspace
      - ./nvim:/root/.config/nvim
    ports:
      - "8081:8080"
      - "8080:3000"
    tty: true
    stdin_open: true
  
